
//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3354 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2011.02.21 at 04:25:09 PM PST 
//
package common;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
* <p>Java class for locator element declaration.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;element name="locator">
*   &lt;complexType>
*     &lt;complexContent>
*       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;/restriction>
*     &lt;/complexContent>
*   &lt;/complexType>
* &lt;/element>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "content"
})
@XmlRootElement(name = "locator")
public class Locator {

 @XmlValue
 protected String content;

 /**
  * Gets the value of the content property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getContent() {
     return content;
 }

 /**
  * Sets the value of the content property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setContent(String value) {
     this.content = value;
 }

}
